spring:
  main:
    web-application-type: none
    banner-mode: off

  # Default datasource config
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:your_db_name}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver

  shell:
    interactive:
      enabled: true

# Custom AWS Configuration (Outside of 'spring')
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY:}
  s3:
    bucket: ${S3_BUCKET_NAME:my-company-files}
    region: ${S3_REGION:us-east-1}
